### ISSUE TITLE
Undistort problem

### ISSUE THREAD

**Issue by CurssedCoffin** [jakarto3d/py-OCamCalib#1]
Your work is perfect. I want to know the diffrence between the fov param fov in your undistort code and the ScaleFactor param in matlab undistortFisheyeImage function. Thank you

**Comment by HugoVazquez-x** [comment]
Hey CurssedCoffin,

Sorry for delay but here is my answer.

A perspective camera is defined with the following model: $tan(\frac{fov_x}{2}) = \frac{sensorsize_x}{2 f}$ with $f$ the focal length. So, in my function $cam2perspectiveindirect()$, I let the users defined $fov$ and $sensorsize$ as parameters and the focal length $f$ is then computed according to the above formula. 

I don't have access to the Matlab source code. However, based on their documentation  ["Scale factor for the focal length of a virtual camera perspective, in pixels, specified as a scalar or an [sx sy] vector. Specify a vector to scale the x and y axes individually. Increase the scale to zoom in the perspective of the camera view." ](https://www.mathworks.com/help/vision/ref/undistortfisheyeimage.html). So, I guess that they normalise the $sensorsize$ parameter to one and so $ScaleFactor = \frac{1}{2 *tan(\frac{fov}{2})} = f$. If you increase ScaleFactor you zoom in because focal length increase otherwise you zoom out.

To conclude, the two parameters $fov$ and $sensorsize$ in my code are condensed in a single one name $ScaleFactor$ in the Matlab code but behavior are the same. 

I hope this helps! Let me know if you have any questions or concerns.

**Comment by CurssedCoffin** [comment]
Thanks dude. Your answer actually solved my problem.

**Comment by CurssedCoffin** [comment]
The line
```python
f = np.max(sensor_size) / (2 * np.tan(np.deg2rad(fov / 2)))
```
can be simply replaced with
```python
f = np.min(sensor_size) / 2 * scaleFactor
```
In matlab, the file undistortFisheyeImage.m indicates a simple focal length
